apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  SQL_USER: c3FsYWRtaW53UHY2NjUx
  SQL_PASSWORD: YUM2dHo3R2Iy
  SQL_SERVER: c3Fsc2VydmVyd3B2NjY1MS5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DBNAME: bXlkcml2aW5nREI=
  
