apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-group-web-read-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-read
subjects:
- kind: Group
  namespace: web
  name: 291ff220-7d11-492b-929b-36c5fe1cf861