apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-group-api-read-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-read
subjects:
- kind: Group
  namespace: api
  name: e491344d-069f-408d-9d2a-d8dad9277153